### ISSUE TITLE
Use cloud-config mounts for fstab

### ISSUE THREAD

**Issue by jozsi** [binxio/ec2-boot-mount-ebs-volume#1]
Hello,

I wonder, wouldn't it be possible to use the [mounts](https://cloudinit.readthedocs.io/en/latest/topics/modules.html#mounts) module of `cloud-config` to handle the `/etc/fstab` related stuff, like the following?
```
mounts:
  - [ /dev/nvme1n1, /var/lib/mongodb, xfs ]
```

Thank you!

**Comment by mvanholsteijn** [comment]
The little script was created for Amazon Linux 1. The `mounts` will only generate an fstab entry for you. To format the disk, you will need to use a `fs_setup` and `disk_setup` config, which is not available in Amazon Linux 1.  Even that may not help as the volume may not be attached at the moment cloud-init runs.

With Amazon Linux 2 I would experiment with a systemd.mount unit (https://www.freedesktop.org/software/systemd/man/systemd.mount.html)

**Comment by jozsi** [comment]
What I meant is that the last two commands of the generated `bootcmd` could be potentially replaced by that `mounts` entry, like this:
```
  bootcmd:
    - mkdir -p /var/mqm
    - while [ ! -b $(readlink -f /dev/xvdd) ]; do echo "waiting for device /dev/xvdd"; sleep 5 ; done
    - blkid $(readlink -f /dev/xvdd) || mkfs -t ext4 $(readlink -f /dev/xvdd)
    - e2label $(readlink -f /dev/xvdd) wmq-data
  mounts:
    - [ LABEL=wmq-data, /var/mqm, ext4 ]
```

Anyhow, your blog article spared me a lot of headaches, especially the way to detect when an EBS volume mounts on a Nitro instance. Thanks for it!
